const searchDumyData = [
  {
    eventName: "Event1",
    location: "Location 1",
    category: "hobbies",
    date: "tomorrow",
    eventsOnly: true,
    input: "User 1",
    onlineEvents: false,
  },
  {
    eventName: "Event1",
    location: "Location 2",
    category: "business",
    date: "tomorrow",
    eventsOnly: false,
    input: "User 2",
    onlineEvents: true,
  },
  {
    eventName: "Event1",
    location: "Location 3",
    category: "music",
    date: "today",
    eventsOnly: false,
    input: "User 3",
    onlineEvents: true,
  },
  {
    eventName: "Event1",
    location: "Location 4",
    category: "home_lifestyle",
    date: "today",
    eventsOnly: true,
    input: "User 4",
    onlineEvents: false,
  },
  {
    eventName: "Event1",
    location: "Location 5",
    category: "family_education",
    date: "weekend",
    eventsOnly: true,
    input: "User 5",
    onlineEvents: false,
  },
  {
    eventName: "Event1",
    location: "Location 6",
    category: "music",
    date: "today",
    eventsOnly: false,
    input: "User 6",
    onlineEvents: true,
  },
  {
    eventName: "Event1",
    location: "Location 7",
    category: "business",
    date: "today",
    eventsOnly: true,
    input: "User 7",
    onlineEvents: true,
  },
  {
    eventName: "Event1",
    location: "Location 8",
    category: "charity_causes",
    date: "weekend",
    eventsOnly: true,
    input: "User 8",
    onlineEvents: true,
  },
  {
    eventName: "Event1",
    location: "Location 9",
    category: "film_media",
    date: "today",
    eventsOnly: false,
    input: "User 9",
    onlineEvents: false,
  },
  {
    eventName: "Eve210",
    location: "Location 10",
    category: "charity_causes",
    date: "tomorrow",
    eventsOnly: false,
    input: "User 10",
    onlineEvents: false,
  },
  {
    eventName: "Event2",
    location: "Location 11",
    category: "home_lifestyle",
    date: "weekend",
    eventsOnly: true,
    input: "User 11",
    onlineEvents: true,
  },
  {
    eventName: "Event2",
    location: "Location 12",
    category: "family_education",
    date: "tomorrow",
    eventsOnly: false,
    input: "User 12",
    onlineEvents: true,
  },
  {
    eventName: "Event2",
    location: "Location 13",
    category: "community",
    date: "weekend",
    eventsOnly: false,
    input: "User 13",
    onlineEvents: true,
  },
  {
    eventName: "Event2",
    location: "Location 14",
    category: "health",
    date: "weekend",
    eventsOnly: false,
    input: "User 14",
    onlineEvents: true,
  },
  {
    eventName: "Event2",
    location: "Location 15",
    category: "fashion",
    date: "tomorrow",
    eventsOnly: false,
    input: "User 15",
    onlineEvents: true,
  },
  {
    eventName: "Event2",
    location: "Location 16",
    category: "fashion",
    date: "weekend",
    eventsOnly: true,
    input: "User 16",
    onlineEvents: true,
  },
  {
    eventName: "Event2",
    location: "Location 17",
    category: "hobbies",
    date: "today",
    eventsOnly: true,
    input: "User 17",
    onlineEvents: false,
  },
  {
    eventName: "Event2",
    location: "Location 18",
    category: "charity_causes",
    date: "weekend",
    eventsOnly: true,
    input: "User 18",
    onlineEvents: false,
  },
  {
    eventName: "Event2",
    location: "Location 19",
    category: "hobbies",
    date: "today",
    eventsOnly: true,
    input: "User 19",
    onlineEvents: true,
  },
  {
    eventName: "Event3",
    location: "Location 20",
    category: "charity_causes",
    date: "today",
    eventsOnly: true,
    input: "User 20",
    onlineEvents: false,
  },
  {
    eventName: "Event3",
    location: "Location 21",
    category: "community",
    date: "weekend",
    eventsOnly: true,
    input: "User 21",
    onlineEvents: false,
  },
  {
    eventName: "Event3",
    location: "Location 22",
    category: "health",
    date: "tomorrow",
    eventsOnly: false,
    input: "User 22",
    onlineEvents: true,
  },
  {
    eventName: "Event3",
    location: "Location 23",
    category: "business",
    date: "weekend",
    eventsOnly: false,
    input: "User 23",
    onlineEvents: false,
  },
  {
    eventName: "Event3",
    location: "Location 24",
    category: "community",
    date: "weekend",
    eventsOnly: false,
    input: "User 24",
    onlineEvents: false,
  },
  {
    eventName: "Event3",
    location: "Location 25",
    category: "charity_causes",
    date: "weekend",
    eventsOnly: false,
    input: "User 25",
    onlineEvents: false,
  },
  {
    eventName: "Event3",
    location: "Location 26",
    category: "community",
    date: "tomorrow",
    eventsOnly: false,
    input: "User 26",
    onlineEvents: false,
  },
  {
    eventName: "Event3",
    location: "Location 27",
    category: "film_media",
    date: "weekend",
    eventsOnly: false,
    input: "User 27",
    onlineEvents: true,
  },
  {
    eventName: "Event3",
    location: "Location 28",
    category: "home_lifestyle",
    date: "today",
    eventsOnly: true,
    input: "User 28",
    onlineEvents: true,
  },
  {
    eventName: "Event3",
    location: "Location 29",
    category: "family_education",
    date: "today",
    eventsOnly: false,
    input: "User 29",
    onlineEvents: true,
  },
  {
    eventName: "Eve430",
    location: "Location 30",
    category: "hobbies",
    date: "weekend",
    eventsOnly: false,
    input: "User 30",
    onlineEvents: false,
  },
  {
    eventName: "Event4",
    location: "Location 31",
    category: "health",
    date: "weekend",
    eventsOnly: true,
    input: "User 31",
    onlineEvents: true,
  },
  {
    eventName: "Event4",
    location: "Location 32",
    category: "health",
    date: "weekend",
    eventsOnly: true,
    input: "User 32",
    onlineEvents: false,
  },
  {
    eventName: "Event4",
    location: "Location 33",
    category: "family_education",
    date: "tomorrow",
    eventsOnly: false,
    input: "User 33",
    onlineEvents: true,
  },
  {
    eventName: "Event4",
    location: "Location 34",
    category: "home_lifestyle",
    date: "weekend",
    eventsOnly: true,
    input: "User 34",
    onlineEvents: true,
  },
  {
    eventName: "Event4",
    location: "Location 35",
    category: "community",
    date: "tomorrow",
    eventsOnly: true,
    input: "User 35",
    onlineEvents: true,
  },
  {
    eventName: "Event4",
    location: "Location 36",
    category: "music",
    date: "today",
    eventsOnly: true,
    input: "User 36",
    onlineEvents: false,
  },
  {
    eventName: "Event4",
    location: "Location 37",
    category: "community",
    date: "weekend",
    eventsOnly: true,
    input: "User 37",
    onlineEvents: false,
  },
  {
    eventName: "Event4",
    location: "Location 38",
    category: "health",
    date: "tomorrow",
    eventsOnly: true,
    input: "User 38",
    onlineEvents: false,
  },
  {
    eventName: "Event4",
    location: "Location 39",
    category: "hobbies",
    date: "tomorrow",
    eventsOnly: false,
    input: "User 39",
    onlineEvents: true,
  },
  {
    eventName: "Event5",
    location: "Location 40",
    category: "hobbies",
    date: "today",
    eventsOnly: false,
    input: "User 40",
    onlineEvents: true,
  },
  {
    eventName: "Event5",
    location: "Location 41",
    category: "music",
    date: "today",
    eventsOnly: true,
    input: "User 41",
    onlineEvents: false,
  },
  {
    eventName: "Event5",
    location: "Location 42",
    category: "family_education",
    date: "tomorrow",
    eventsOnly: false,
    input: "User 42",
    onlineEvents: true,
  },
  {
    eventName: "Event5",
    location: "Location 43",
    category: "family_education",
    date: "today",
    eventsOnly: false,
    input: "User 43",
    onlineEvents: false,
  },
  {
    eventName: "Event5",
    location: "Location 44",
    category: "community",
    date: "today",
    eventsOnly: true,
    input: "User 44",
    onlineEvents: false,
  },
  {
    eventName: "Event5",
    location: "Location 45",
    category: "music",
    date: "today",
    eventsOnly: false,
    input: "User 45",
    onlineEvents: false,
  },
  {
    eventName: "Event5",
    location: "Location 46",
    category: "hobbies",
    date: "weekend",
    eventsOnly: false,
    input: "User 46",
    onlineEvents: false,
  },
  {
    eventName: "Event5",
    location: "Location 47",
    category: "music",
    date: "tomorrow",
    eventsOnly: false,
    input: "User 47",
    onlineEvents: false,
  },
  {
    eventName: "Event5",
    location: "Location 48",
    category: "family_education",
    date: "today",
    eventsOnly: true,
    input: "User 48",
    onlineEvents: true,
  },
  {
    eventName: "Event5",
    location: "Location 49",
    category: "charity_causes",
    date: "today",
    eventsOnly: true,
    input: "User 49",
    onlineEvents: false,
  },
  {
    eventName: "Event6",
    location: "Location 50",
    category: "business",
    date: "today",
    eventsOnly: false,
    input: "User 50",
    onlineEvents: false,
  },
  {
    eventName: "Event6",
    location: "Location 51",
    category: "charity_causes",
    date: "tomorrow",
    eventsOnly: true,
    input: "User 51",
    onlineEvents: true,
  },
  {
    eventName: "Event6",
    location: "Location 52",
    category: "food_drink",
    date: "today",
    eventsOnly: false,
    input: "User 52",
    onlineEvents: true,
  },
  {
    eventName: "Event6",
    location: "Location 53",
    category: "home_lifestyle",
    date: "today",
    eventsOnly: true,
    input: "User 53",
    onlineEvents: false,
  },
  {
    eventName: "Event6",
    location: "Location 54",
    category: "business",
    date: "tomorrow",
    eventsOnly: false,
    input: "User 54",
    onlineEvents: true,
  },
  {
    eventName: "Event6",
    location: "Location 55",
    category: "film_media",
    date: "tomorrow",
    eventsOnly: false,
    input: "User 55",
    onlineEvents: false,
  },
  {
    eventName: "Event6",
    location: "Location 56",
    category: "health",
    date: "tomorrow",
    eventsOnly: true,
    input: "User 56",
    onlineEvents: true,
  },
  {
    eventName: "Event6",
    location: "Location 57",
    category: "home_lifestyle",
    date: "tomorrow",
    eventsOnly: true,
    input: "User 57",
    onlineEvents: true,
  },
  {
    eventName: "Event6",
    location: "Location 58",
    category: "film_media",
    date: "today",
    eventsOnly: true,
    input: "User 58",
    onlineEvents: true,
  },
  {
    eventName: "Event6",
    location: "Location 59",
    category: "home_lifestyle",
    date: "weekend",
    eventsOnly: false,
    input: "User 59",
    onlineEvents: false,
  },
  {
    eventName: "Event7",
    location: "Location 60",
    category: "music",
    date: "tomorrow",
    eventsOnly: true,
    input: "User 60",
    onlineEvents: false,
  },
  {
    eventName: "Event7",
    location: "Location 61",
    category: "food_drink",
    date: "weekend",
    eventsOnly: true,
    input: "User 61",
    onlineEvents: true,
  },
  {
    eventName: "Event7",
    location: "Location 62",
    category: "music",
    date: "weekend",
    eventsOnly: false,
    input: "User 62",
    onlineEvents: false,
  },
  {
    eventName: "Event7",
    location: "Location 63",
    category: "community",
    date: "today",
    eventsOnly: false,
    input: "User 63",
    onlineEvents: false,
  },
  {
    eventName: "Event7",
    location: "Location 64",
    category: "business",
    date: "today",
    eventsOnly: false,
    input: "User 64",
    onlineEvents: true,
  },
  {
    eventName: "Event7",
    location: "Location 65",
    category: "health",
    date: "weekend",
    eventsOnly: true,
    input: "User 65",
    onlineEvents: false,
  },
  {
    eventName: "Event7",
    location: "Location 66",
    category: "hobbies",
    date: "tomorrow",
    eventsOnly: false,
    input: "User 66",
    onlineEvents: false,
  },
  {
    eventName: "Event7",
    location: "Location 67",
    category: "family_education",
    date: "weekend",
    eventsOnly: true,
    input: "User 67",
    onlineEvents: true,
  },
  {
    eventName: "Event7",
    location: "Location 68",
    category: "community",
    date: "tomorrow",
    eventsOnly: true,
    input: "User 68",
    onlineEvents: false,
  },
  {
    eventName: "Event7",
    location: "Location 69",
    category: "film_media",
    date: "weekend",
    eventsOnly: true,
    input: "User 69",
    onlineEvents: true,
  },
  {
    eventName: "Event7",
    location: "Location 70",
    category: "film_media",
    date: "tomorrow",
    eventsOnly: true,
    input: "User 70",
    onlineEvents: true,
  },
  {
    eventName: "Event7",
    location: "Location 71",
    category: "music",
    date: "tomorrow",
    eventsOnly: true,
    input: "User 71",
    onlineEvents: false,
  },
  {
    eventName: "Event7",
    location: "Location 72",
    category: "film_media",
    date: "tomorrow",
    eventsOnly: true,
    input: "User 72",
    onlineEvents: true,
  },
  {
    eventName: "Event7",
    location: "Location 73",
    category: "food_drink",
    date: "tomorrow",
    eventsOnly: false,
    input: "User 73",
    onlineEvents: false,
  },
  {
    eventName: "Event7",
    location: "Location 74",
    category: "food_drink",
    date: "today",
    eventsOnly: false,
    input: "User 74",
    onlineEvents: false,
  },
  {
    eventName: "Event7",
    location: "Location 75",
    category: "business",
    date: "today",
    eventsOnly: true,
    input: "User 75",
    onlineEvents: false,
  },
  {
    eventName: "Event7",
    location: "Location 76",
    category: "business",
    date: "tomorrow",
    eventsOnly: true,
    input: "User 76",
    onlineEvents: true,
  },
  {
    eventName: "Event7",
    location: "Location 77",
    category: "hobbies",
    date: "weekend",
    eventsOnly: true,
    input: "User 77",
    onlineEvents: false,
  },
  {
    eventName: "Event7",
    location: "Location 78",
    category: "film_media",
    date: "weekend",
    eventsOnly: false,
    input: "User 78",
    onlineEvents: true,
  },
  {
    eventName: "Event7",
    location: "Location 79",
    category: "charity_causes",
    date: "tomorrow",
    eventsOnly: true,
    input: "User 79",
    onlineEvents: true,
  },
  {
    eventName: "Event7",
    location: "Location 80",
    category: "charity_causes",
    date: "weekend",
    eventsOnly: true,
    input: "User 80",
    onlineEvents: false,
  },
  {
    eventName: "Event7",
    location: "Location 81",
    category: "film_media",
    date: "tomorrow",
    eventsOnly: false,
    input: "User 81",
    onlineEvents: false,
  },
  {
    eventName: "Event7",
    location: "Location 82",
    category: "food_drink",
    date: "tomorrow",
    eventsOnly: true,
    input: "User 82",
    onlineEvents: false,
  },
  {
    eventName: "Event7",
    location: "Location 83",
    category: "health",
    date: "tomorrow",
    eventsOnly: false,
    input: "User 83",
    onlineEvents: true,
  },
  {
    eventName: "Event7",
    location: "Location 84",
    category: "hobbies",
    date: "today",
    eventsOnly: true,
    input: "User 84",
    onlineEvents: true,
  },
  {
    eventName: "Event7",
    location: "Location 85",
    category: "family_education",
    date: "weekend",
    eventsOnly: true,
    input: "User 85",
    onlineEvents: false,
  },
  {
    eventName: "Event7",
    location: "Location 86",
    category: "community",
    date: "weekend",
    eventsOnly: true,
    input: "User 86",
    onlineEvents: false,
  },
  {
    eventName: "Event7",
    location: "Location 87",
    category: "business",
    date: "today",
    eventsOnly: false,
    input: "User 87",
    onlineEvents: false,
  },
  {
    eventName: "Event7",
    location: "Location 88",
    category: "food_drink",
    date: "weekend",
    eventsOnly: false,
    input: "User 88",
    onlineEvents: false,
  },
  {
    eventName: "Event7",
    location: "Location 89",
    category: "health",
    date: "today",
    eventsOnly: false,
    input: "User 89",
    onlineEvents: false,
  },
  {
    eventName: "Event7",
    location: "Location 90",
    category: "home_lifestyle",
    date: "weekend",
    eventsOnly: false,
    input: "User 90",
    onlineEvents: false,
  },
  {
    eventName: "Event7",
    location: "Location 91",
    category: "hobbies",
    date: "tomorrow",
    eventsOnly: false,
    input: "User 91",
    onlineEvents: true,
  },
  {
    eventName: "Event7",
    location: "Location 92",
    category: "hobbies",
    date: "today",
    eventsOnly: false,
    input: "User 92",
    onlineEvents: false,
  },
  {
    eventName: "Event7",
    location: "Location 93",
    category: "fashion",
    date: "today",
    eventsOnly: true,
    input: "User 93",
    onlineEvents: true,
  },
  {
    eventName: "Event7",
    location: "Location 94",
    category: "community",
    date: "weekend",
    eventsOnly: false,
    input: "User 94",
    onlineEvents: true,
  },
  {
    eventName: "Event7",
    location: "Location 95",
    category: "business",
    date: "tomorrow",
    eventsOnly: true,
    input: "User 95",
    onlineEvents: true,
  },
  {
    eventName: "Event7",
    location: "Location 96",
    category: "food_drink",
    date: "today",
    eventsOnly: false,
    input: "User 96",
    onlineEvents: true,
  },
  {
    eventName: "Event7",
    location: "Location 97",
    category: "community",
    date: "today",
    eventsOnly: true,
    input: "User 97",
    onlineEvents: false,
  },
  {
    eventName: "Event7",
    location: "Location 98",
    category: "business",
    date: "today",
    eventsOnly: false,
    input: "User 98",
    onlineEvents: false,
  },
  {
    eventName: "Event7",
    location: "Location 99",
    category: "health",
    date: "weekend",
    eventsOnly: true,
    input: "User 99",
    onlineEvents: false,
  },
  {
    eventName: "Event8",
    location: "Location 100",
    category: "home_lifestyle",
    date: "weekend",
    eventsOnly: true,
    input: "User 100",
    onlineEvents: true,
  },
];
export default searchDumyData;
